use_frameworks!

platform :ios, '10.0'

target 'ArcProgressView_Example' do
  pod 'ArcProgressView', :path => '../'

  target 'ArcProgressView_Tests' do
    inherit! :search_paths
    use_frameworks!

    pod 'Nimble'
  end
end
