use_frameworks!

platform :ios, '8.0'

target 'CircularProgressView_Example' do
  pod 'CircularProgressView', :path => '../'

  target 'CircularProgressView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
